### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by exterm** [JanAhrens/arbeit#1]
Could serve as documentation, too. On first glance, I did not understand how to use the `break` option correctly.

**Comment by JanAhrens** [comment]
I wrote [unit_tests.py](https://github.com/JanAhrens/arbeit/blob/84e3a75f8054d5e27fd0211c74d4f58286ba0f35/unit_tests.py) and [integration_tests.py](https://github.com/JanAhrens/arbeit/blob/84e3a75f8054d5e27fd0211c74d4f58286ba0f35/integration_tests.py). Feel free to review them :smiley:

Python's `argparse` generates documentation automatically:

> arbeit break -h

**Comment by exterm** [comment]
Nice! Just one question out of interest. Your integration tests seem to depend on implementation details (in which format you persist the data).

You could have avoided that by letting your tests hit the database and testing that saving and loading the schedule returns the same schedule. Or have I overlooked the real reason to mock the database operations?

**Comment by JanAhrens** [comment]
That's a good question. I wanted to prevent the tests from writing on the filesystem. Having the database format in there is definitely not ideal. Maybe I'll change it in the future.
